---
securityContextCrossplane:
  runAsUser: null
  runAsGroup: null
securityContextRBACManager:
  runAsUser: null
  runAsGroup: null
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
